// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4j6uu98kfxeWPAFdAB7FdC2LskPs80i8',
    appId: '1:655422347848:web:faa71609fadef51d3ed67d',
    messagingSenderId: '655422347848',
    projectId: 'fuellevel-5c083',
    authDomain: 'fuellevel-5c083.firebaseapp.com',
    databaseURL: 'https://fuellevel-5c083-default-rtdb.firebaseio.com',
    storageBucket: 'fuellevel-5c083.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqJU661_X9lbweDRJOd2tSiaLwJZic3Fo',
    appId: '1:655422347848:android:20ac4d12f7f5ec523ed67d',
    messagingSenderId: '655422347848',
    projectId: 'fuellevel-5c083',
    databaseURL: 'https://fuellevel-5c083-default-rtdb.firebaseio.com',
    storageBucket: 'fuellevel-5c083.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-uiiTFPh3SHVoAPYH2Gv4LAlr8sh0e14',
    appId: '1:655422347848:ios:b596f389ae8f946c3ed67d',
    messagingSenderId: '655422347848',
    projectId: 'fuellevel-5c083',
    databaseURL: 'https://fuellevel-5c083-default-rtdb.firebaseio.com',
    storageBucket: 'fuellevel-5c083.appspot.com',
    iosBundleId: 'com.fuellevel.fuellevelMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-uiiTFPh3SHVoAPYH2Gv4LAlr8sh0e14',
    appId: '1:655422347848:ios:b596f389ae8f946c3ed67d',
    messagingSenderId: '655422347848',
    projectId: 'fuellevel-5c083',
    databaseURL: 'https://fuellevel-5c083-default-rtdb.firebaseio.com',
    storageBucket: 'fuellevel-5c083.appspot.com',
    iosBundleId: 'com.fuellevel.fuellevelMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4j6uu98kfxeWPAFdAB7FdC2LskPs80i8',
    appId: '1:655422347848:web:edbabcfa79b59f643ed67d',
    messagingSenderId: '655422347848',
    projectId: 'fuellevel-5c083',
    authDomain: 'fuellevel-5c083.firebaseapp.com',
    databaseURL: 'https://fuellevel-5c083-default-rtdb.firebaseio.com',
    storageBucket: 'fuellevel-5c083.appspot.com',
  );
}
